### ISSUE TITLE
Need instructions to get started with this project

### ISSUE THREAD

**Issue by shubhamdhanetia** [WolfgangOfner/MicroserviceDemo#4]
As I am new to Docker, can you tell us the instructions step by step to get started?
When I run docker-compose up command, I am getting an error

![image](https://user-images.githubusercontent.com/71070755/99622147-8fe71080-2a4f-11eb-94a1-4764d8651059.png)

**Comment by WolfgangOfner** [comment]
Hi shubhamdhanetia,

sorry for the late reply. You haven't done anything wrong. I deleted the latest tag, therefore docker can't pull it. I added the latest tag again but the containers are not starting at the moment. I will take a look at this in the next couple of days.

For now, you can use "docker-compose -f docker-compose.Build.yml up -d" to build the container locally. This will take a couple of minutes but then all containers should be running and accessible on their ports.

**Comment by WolfgangOfner** [comment]
I updated the docker-compose file not use a certificate for now.

Now running docker-compose should work again.

**Comment by shubhamdhanetia** [comment]
Thanks @WolfgangOfner  ! And Sorry for the delay in response. I will try it again!
