### ISSUE TITLE
Already closed: The AMQP operation was interrupted: AMQP close-reason,

### ISSUE THREAD

**Issue by hyihao** [WolfgangOfner/MicroserviceDemo#5]
![image](https://user-images.githubusercontent.com/1115391/103404987-7aa5eb80-4b90-11eb-9c0e-a94251080e5d.png)

**Comment by WolfgangOfner** [comment]
Hi hyihao,

could you please post some more information how you got this exception? I can't reproduce it on my side.

Thank you

**Comment by WolfgangOfner** [comment]
Closed due to inactivity
