### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tarakeswarab** [WolfgangOfner/MicroserviceDemo#6]
I am getting the error

ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN
while creation of connection

**Comment by Tarakeswarab** [comment]
The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=406, text="PRECONDITION_FAILED - inequivalent arg 'durable'

**Comment by Tarakeswarab** [comment]
ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN
while creation of connection -it is resolved

**Comment by WolfgangOfner** [comment]
Hi Tarakeswarb,

do you still have any problems or are all resolved?

If there is still a problem, please post what you did to get the error.

Thank you.

**Comment by Tarakeswarab** [comment]
Thank you, It has been resolved.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
